[package]
name = "hk8s"
version = "0.1.0"
edition = "2021"

[dependencies]
kube = { version = "0.90", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.21.1", features = ["v1_28"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
